version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/konectapp
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Frontend/konectapp-front
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=konectapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
